.github/workflows/tests.yml, co2calculator/calculate.py, co2calculator/distances.py, co2calculator/test/test_distances.py
- Added GitHub secret
- use secret for pytests in GitHub Action workflow
=> Dev actions secrets

co2calculator/calculate.py
fixed major bug, which lead to wrong emission factors queried from the database
=> Major bug fix..

co2calculator/calculate.py
Reverts pledge4future/co2calculator#65
=> Revert "Major bug fix.."

co2calculator/calculate.py
fixed major bug, which lead to wrong emission factors queried from the database
=> Fixes in calculate.py

.github/workflows/tests.yml
=> Remove python<3.9 from CI

co2calculator/calculate.py, co2calculator/distances.py, requirements.txt, tests/unit/test_calculate.py
Waits for #79 to be merged first!
=> Separate distance calculation

co2calculator/calculate.py, co2calculator/distances.py, tests/unit/test_calculate.py
- let transport co2 calc functions return only emissions
- update business trips and commuting function accordingly
- update unit tests accordingly
- update docstrings
closes #83
=> let transport co2 calc functions return only emissions

co2calculator/calculate.py, co2calculator/constants.py, co2calculator/distances.py
=> move TransportationMode to constants.py and use it globally

co2calculator/constants.py, co2calculator/distances.py, requirements.txt, tests/test_distances.py, tests/unit/test_calculate.py
=> Mock tests, introduce new pydantic models

.gitignore, co2calculator/__init__.py, co2calculator/calculate.py, co2calculator/constants.py, requirements.txt, run_calculate.py
(work from an "old" branch)
* add additional enums, esp. TransportationModes specific for Business Trips and Commuting (yet to be used)
=> Dev additional enums

co2calculator/calculate.py, tests/test_distances.py
and add test for `_apply_detour()` function
=> Add function `get_conversion_factor()`

co2calculator/constants.py, co2calculator/distances.py, tests/test_distances.py
You might want to have a look @redfrexx @veitu
=> initial ORS-based implementation of calculating ferry trip distances

.github/workflows/documentation.yml, .gitignore
=> 140 docs pipeline

.github/workflows/documentation.yml, .gitignore, docs/calculate/heating_electricity.rst
I created a workflow to host the existing sphinx docu via GitHub pages. Check out the hosted version here: https://pledge4future.github.io/co2calculator/
Documentation should get updated automatically with every commit to the main branch. 
Closes #140
=> Automate documentation update and hosting

docs/_static/css-style.css, docs/conf.py, docs/index.rst, docs/tutorial.md
edit theme styling and add some code examples as poc
=> docs: styling and content enhancement

docs/_templates/autosummary/class.rst, docs/_templates/autosummary/function.rst, docs/api.rst, docs/commuting.rst, docs/conf.py, docs/index.rst
Added auto generated API docu for functions/classes.
=> docs: add autosummary documentation

.github/ISSUE_TEMPLATE/BUG-REPORT.yml, .github/ISSUE_TEMPLATE/FEATURE-REQUEST.yml, .github/ISSUE_TEMPLATE/config.yml
Add templates for bugs and feature requests
=> core: add templates and config

.github/workflows/ci-development.yml, .github/workflows/ci-production.yml, pyproject.toml, tests/unit/api/test_trip.py, tests/unit/test_distances.py
=> mark ORS tests instead of skipping, add ORS key secret to GitHub actions (fixes #199)

co2calculator/api/trip.py, tests/unit/api/test_trip.py
=> add option for trip with known emission factor

co2calculator/api/energy.py, co2calculator/api/trip.py, co2calculator/constants.py, co2calculator/data_handlers.py, co2calculator/distances.py, co2calculator/energy/calculate_energy.py, co2calculator/mobility/calculate_mobility.py
=> Revise docstrings

co2calculator/api/energy.py, co2calculator/constants.py, co2calculator/data/emission_factors_heating.csv, co2calculator/data_handlers.py, co2calculator/energy/calculate_energy.py, co2calculator/mobility/calculate_mobility.py, co2calculator/parameters.py, tests/functional/test_data_code_compliance.py, tests/unit/api/test_energy.py, tests/unit/test_parameters.py
=> Make sure own_share is properly passed
